trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'fjdwinfraregistry-connection'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'